/* Publicly documented Kurkumbh MIDC company references.
   Exact coordinates are intentionally omitted unless independently verified.
   Use the Google Maps search links generated by main.js. */
window.kurkumbhCompanies = [
  {
    name: "Cargill India Pvt. Ltd.",
    plot: "E-4 / E-45, MIDC Kurkumbh",
    type: "Food processing / food ingredients",
    verification: "Public government record"
  },
  {
    name: "Clean Science & Technology Ltd.",
    plot: "D-26 / D-28, MIDC Kurkumbh",
    type: "Specialty chemicals",
    verification: "Public government record"
  },
  {
    name: "Cipla Ltd.",
    plot: "D-7 / D-7/8 / D-22 / D-27, MIDC Kurkumbh",
    type: "Pharmaceuticals",
    verification: "Company disclosure / public record"
  },
  {
    name: "Honour Lab Ltd.",
    plot: "D-10 / A-88, MIDC Kurkumbh",
    type: "Pharmaceuticals / APIs",
    verification: "Public government record"
  },
  {
    name: "Alkyl Amines Chemicals Ltd.",
    plot: "D-6/1 & D-6/2, MIDC Kurkumbh",
    type: "Specialty chemicals",
    verification: "Public government record"
  },
  {
    name: "Glenmark Life Sciences / Alivus-related Kurkumbh facility",
    plot: "A-80, MIDC Kurkumbh",
    type: "APIs / pharmaceuticals",
    verification: "Public government record"
  }
];
